\c smartcare_db;

SET ROLE SMARTCARE;

CREATE TABLE TIPODISPOSITIVO 
(
  IDTIPO SERIAL,
  NOME VARCHAR(40) NOT NULL,
  IND_SIT INT,
  PRIMARY KEY (IDTIPO)
);

CREATE TABLE DISPOSITIVO 
(   
  IDDISPOSITIVO SERIAL ,
  CODIGODISPOSITIVO VARCHAR(40) NULL ,
  IDTIPO INT NULL ,
  IDAMBIENTE INT NULL ,
  NOME VARCHAR(40) NULL ,
  DESCRICAO VARCHAR(200) NULL ,
  EIXO_X FLOAT NULL ,
  EIXO_Y FLOAT NULL ,
  ORIENTACAO CHAR(2) ,
  IND_SIT INT ,
  PRIMARY KEY (IDDISPOSITIVO) ,
  FOREIGN KEY (IDTIPO) REFERENCES TIPODISPOSITIVO(IDTIPO) ,
  UNIQUE(CODIGODISPOSITIVO)
);

CREATE TABLE AMBIENTE 
(
  IDAMBIENTE SERIAL ,  
  NOME VARCHAR(40) NOT NULL ,
  DESCRICAO VARCHAR(200) NULL ,
  IND_SIT INT ,
  PRIMARY KEY (IDAMBIENTE)
);

CREATE TABLE MEDICAO 
(
  IDMEDICAO SERIAL ,
  IDDISPOSITIVO INT NULL ,
  DATAHORA TIMESTAMP NULL ,
  VALOR VARCHAR(10) NULL ,
  UNIDADE CHAR(4) NULL ,
  IND_SIT INT ,
  PRIMARY KEY (IDMEDICAO) ,
  FOREIGN KEY (IDDISPOSITIVO) REFERENCES DISPOSITIVO(IDDISPOSITIVO)
);

CREATE TABLE USUARIO
(
  USUARIOID SERIAL ,
  NOME VARCHAR(400) ,
  EMAIL VARCHAR(200) ,
  SENHA VARCHAR(200) ,
  IND_SIT INT ,
  UNIQUE(EMAIL)
);

CREATE TABLE ENFERMIDADE
(
  IDENFERMIDADE SERIAL ,
  NOME VARCHAR(100) ,
  DESCRICAO VARCHAR(400) NULL ,
  IND_SIT INT ,
  PRIMARY KEY (IDENFERMIDADE)
);

CREATE TABLE ESTADO
(
  IDESTADO SERIAL ,
  NOME VARCHAR(100) ,
  UF VARCHAR(5) ,
  PRIMARY KEY (IDESTADO)
);

CREATE TABLE CIDADE
(
  IDCIDADE SERIAL ,
  IDESTADO INT ,
  NOME VARCHAR(200) ,
  PRIMARY KEY (IDCIDADE) ,
  FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO)
);

CREATE TABLE PACIENTE
(
  IDPACIENTE SERIAL ,
  CPF VARCHAR(11) NULL ,
  NOME VARCHAR(400) NULL ,
  NASCIMENTO DATE NULL ,
  IDENFERMIDADE INT NULL ,
  ESTAGIO_ENFERMIDADE VARCHAR(10) NULL ,
  IDESTADO INT NULL ,
  IDCIDADE INT NULL ,
  BAIRRO VARCHAR(100) NULL ,
  ENDERECO VARCHAR(300) NULL ,
  COMPLEMENTO VARCHAR(100) NULL ,
  BIT_ALERTA BOOLEAN NULL ,
  IND_SIT INT ,
  PRIMARY KEY (IDPACIENTE) ,
  FOREIGN KEY (IDENFERMIDADE) REFERENCES ENFERMIDADE(IDENFERMIDADE) ,
  FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO) ,
  FOREIGN KEY (IDCIDADE) REFERENCES CIDADE(IDCIDADE)
);

CREATE TABLE ALERTA
(
  IDALERTA SERIAL ,
  DESCRICAO_ALERTA VARCHAR(300) ,
  HORARIO TIMESTAMP ,
  IND_SIT INT ,
  PRIMARY KEY (IDALERTA)
)

-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO SMARTCARE;

-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO SMARTCARE;

-- GRANT USAGE ON SCHEMA PUBLIC TO SMARTCARE;
