\c smartcare_db;

SET ROLE SMARTCARE;

CREATE TABLE TIPODISPOSITIVO 
(
  IDTIPO SERIAL,
  NOME VARCHAR(40) NOT NULL,
  IND_SIT INT,
  PRIMARY KEY (IDTIPO)
);

CREATE TABLE DISPOSITIVO 
(   
  IDDISPOSITIVO SERIAL ,
  CODIGODISPOSITIVO VARCHAR(40) NULL ,
  IDTIPO INT NULL ,
  IDAMBIENTE INT NULL ,
  NOME VARCHAR(40) NULL ,
  DESCRICAO VARCHAR(200) NULL ,
  EIXO_X FLOAT NULL ,
  EIXO_Y FLOAT NULL ,
  ORIENTACAO CHAR(2) ,
  IND_SIT INT ,
  PRIMARY KEY (IDDISPOSITIVO) ,
  FOREIGN KEY (IDTIPO) REFERENCES TIPODISPOSITIVO(IDTIPO)
);

CREATE TABLE AMBIENTE 
(
  IDAMBIENTE SERIAL ,  
  NOME VARCHAR(40) NOT NULL ,
  DESCRICAO VARCHAR(200) NULL ,
  IND_SIT INT ,
  PRIMARY KEY (IDAMBIENTE)
);

CREATE TABLE MEDICAO 
(
  IDMEDICAO SERIAL ,
  IDDISPOSITIVO INT NULL ,
  DATAHORA TIMESTAMP NULL ,
  VALOR VARCHAR(10) NULL ,
  UNIDADE CHAR(4) NULL ,
  IND_SIT INT ,
  PRIMARY KEY (IDMEDICAO) ,
  FOREIGN KEY (IDDISPOSITIVO) REFERENCES DISPOSITIVO(IDDISPOSITIVO)
);

CREATE TABLE USUARIO
(
  USUARIOID SERIAL ,
  NOME VARCHAR(400) ,
  EMAIL VARCHAR(200) ,
  SENHA VARCHAR(200) ,
  IND_SIT INT ,
  UNIQUE(EMAIL)
)

-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO SMARTCARE;

-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO SMARTCARE;

-- GRANT USAGE ON SCHEMA PUBLIC TO SMARTCARE;
