\c smartcare_db;

SET ROLE SMARTCARE;

-- FUNCTION: PUBLIC.USP_BUSCA_MEDICAO(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE)

-- DROP FUNCTION IF EXISTS PUBLIC.USP_BUSCA_MEDICAO(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE);

CREATE OR REPLACE FUNCTION PUBLIC.USP_BUSCA_MEDICAO(
	DATA_INICIO TIMESTAMP WITH TIME ZONE,
	DATA_FIM TIMESTAMP WITH TIME ZONE)
    RETURNS TABLE   (
                        IDMEDICAO INT ,
                        IDDISPOSITIVO INT ,
                        DATAHORA TIMESTAMP ,
                        VALOR VARCHAR(10) ,
                        UNIDADE CHAR(4) ,
                        IND_SIT INT
                    )
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $$

DECLARE MED RECORD;

BEGIN

RETURN QUERY
SELECT
    *
FROM    MEDICAO M
WHERE   1 = 1
    AND M.DATAHORA BETWEEN DATA_INICIO AND DATA_FIM;

END
$$;

ALTER FUNCTION PUBLIC.USP_BUSCA_MEDICAO(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE)
    OWNER TO SMARTCARE;